baseURL = "https://mapping-tournai.be/"
title = "Mapping Tournai"
locale = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
buildFuture = true
theme = ["github.com/onweru/compose"]

[pagination]
disableAliases = false
pagerSize = 10
path = "page"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
uniqueHomePage = true
blogDir = "field-notes"
enableDarkMode = false
defaultLightingMode = "auto"
enableCopyright = false
time_format_blog = "2 January 2006"
time_format_default = "2 January 2006"

[params.search]
on = true
global = true

[params.logo]
lightMode = "/images/mapping-tournai.svg"
darkMode = "/images/mapping-tournai-dark.svg"

[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Method"
url = "/methodology/"
weight = 20

[[menu.main]]
name = "Maps"
url = "/maps/"
weight = 30

[[menu.main]]
name = "Capture notes"
url = "/field-notes/"
weight = 40

[[menu.main]]
name = "Open data"
url = "/data/"
weight = 50
